# Generated by Django 4.2.5 on 2023-11-11 19:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Business Name (Razón Social)', max_length=60, verbose_name='Razón social')),
                ('street', models.CharField(help_text='Street', max_length=60, verbose_name='Calle')),
                ('ext_number', models.CharField(help_text='External number', max_length=10, verbose_name='Número exterior')),
                ('int_number', models.CharField(help_text='Internal number', max_length=10, verbose_name='Número interior')),
                ('neighbourhood', models.CharField(help_text='Colonia', max_length=60, verbose_name='Colonia')),
                ('city', models.CharField(help_text='Munucipio', max_length=60, verbose_name='Municipio')),
                ('state', models.CharField(help_text='Estado', max_length=60, verbose_name='Estado')),
                ('zip_code', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')])),
                ('phone', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('[(]?[0-9]{2,3}[)]?[-\\s]?[0-9]{3,4}[-\\s]?[0-9]{4}$')])),
                ('email', models.EmailField(max_length=100)),
            ],
            options={
                'verbose_name': 'Business Info',
                'verbose_name_plural': 'Business Info',
            },
        ),
    ]
