# Generated by Django 4.2.5 on 2023-11-11 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0002_businessinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='Friendly URl slug', max_length=60, unique=True)),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('large_description', models.TextField(verbose_name='Large description')),
                ('image', models.ImageField(blank=True, help_text='Category image', null=True, upload_to='category', verbose_name='Image')),
                ('thumbnail', models.ImageField(blank=True, help_text='Category thumbnail image', null=True, upload_to='category/thumbnail', verbose_name='Thumbnail image')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Creation date', null=True)),
                ('modified_date', models.DateField(auto_now_add=True, help_text='Modified date', null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_categories', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_categories', to=settings.AUTH_USER_MODEL)),
                ('parent_category', models.ForeignKey(blank=True, help_text='The parent category', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='child_categories', to='catalog.category', verbose_name='Parent category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
    ]
