# Generated by Django 4.2.5 on 2023-11-11 21:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0003_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Brand name', max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='Friendly URl slug', max_length=60, unique=True)),
                ('logo', models.ImageField(help_text='Brand logo', upload_to='brand', verbose_name='Brand logo')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name', max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(help_text='Friendly URL slug', max_length=60, unique=True)),
                ('sku', models.CharField(help_text='Stock keeping unit', max_length=15, unique=True, verbose_name='SKU')),
                ('upc', models.CharField(help_text='Universal product code', max_length=12, unique=True, verbose_name='UPC')),
                ('short_description', models.TextField(verbose_name='Short description')),
                ('large_Description', models.TextField(verbose_name='Large description')),
                ('thumbnail', models.ImageField(blank=True, help_text='Product thumbnail', null=True, upload_to='product/thumbnail', verbose_name='Thumbnail image file')),
                ('created_date', models.DateField(auto_now_add=True, help_text='Creation date', null=True)),
                ('modified_date', models.DateField(auto_now_add=True, help_text='Modified date', null=True)),
                ('active', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('brand', models.ForeignKey(help_text='The brand or manufacturer of the product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.brand')),
                ('categories', models.ManyToManyField(help_text='Other categories where the product should be shown', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_product', to=settings.AUTH_USER_MODEL)),
                ('main_category', models.ForeignKey(help_text='The parent category of the product', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Parent category')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_product', to=settings.AUTH_USER_MODEL)),
                ('related_product', models.ManyToManyField(blank=True, help_text='Related products', related_name='related', to='catalog.product', verbose_name='Related products')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
            },
        ),
    ]
