# Generated by Django 5.0 on 2024-01-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_upc'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Product thumbnail', null=True, upload_to='product/thumbnail', verbose_name='Thumbnail image file'),
        ),
    ]
