# Generated by Django 5.0 on 2024-01-25 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Footer section name', max_length=25, verbose_name='Footer Section')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Footer link name', max_length=25, verbose_name='Footer link')),
                ('url', models.CharField(max_length=30)),
                ('footerSection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.footersection')),
            ],
        ),
    ]
