# Generated by Django 4.2.5 on 2023-11-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_contact_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contact'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=60, verbose_name='name'),
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Slider title', max_length=60, unique=True, verbose_name='Title')),
                ('name', models.CharField(help_text='Slider name', max_length=60, unique=True, verbose_name='Name')),
                ('message', models.CharField(help_text='Slider message', max_length=60, unique=True, verbose_name='Message')),
                ('image', models.ImageField(blank=True, help_text='Slider image', null=True, upload_to='slider', verbose_name='Image file')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='catalog.category')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Slider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
