# Generated by Django 4.2.5 on 2023-11-21 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_contact_options_alter_contact_name_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='catalog.category'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slider', to='catalog.product'),
        ),
    ]
