# Generated by Django 4.2.5 on 2023-11-22 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_slider_category_alter_slider_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Promo title', max_length=60, unique=True, verbose_name='Title')),
                ('name', models.CharField(help_text='Promo name', max_length=60, unique=True, verbose_name='Name')),
                ('message', models.CharField(help_text='Promo message', max_length=60, unique=True, verbose_name='Message')),
                ('image', models.ImageField(blank=True, help_text='Promo image', null=True, upload_to='slider', verbose_name='Image file')),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='catalog.category')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Promo',
                'verbose_name_plural': 'Promos',
            },
        ),
    ]
