# Generated by Django 4.2.5 on 2023-11-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='product/thumbnail', verbose_name='Product image file'),
        ),
    ]
