# Generated by Django 4.2.5 on 2023-11-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_productimages_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimages',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='product/product', verbose_name='Product image file'),
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Pricing name', max_length=60, unique=True, verbose_name='Name')),
                ('Discount type', models.CharField(choices=[('p', 'Percentage'), ('d', 'Direct')], default='p', max_length=1, verbose_name='Discount type')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('active', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='catalog.product')),
            ],
        ),
    ]
