# Generated by Django 4.2.5 on 2023-11-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_productimages_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
