# Generated by Django 4.2.5 on 2023-11-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_productprice_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimages',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image', null=True, upload_to='product/', verbose_name='Product image file'),
        ),
    ]
