# Generated by Django 4.2.5 on 2023-12-07 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_feauture_feauturevalue_productfeauturevalue_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filterType', models.CharField(choices=[('sel', 'Dropdown'), ('rad', 'Radio button'), ('chk', 'Checkboxes'), ('rng', 'Range'), ('txt', 'Text')], default='sel', max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='catalog.category')),
                ('filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.feauture')),
            ],
        ),
    ]
