# Generated by Django 4.2.5 on 2023-12-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productprice',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
