# Generated by Django 4.2.5 on 2024-01-30 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_footersection_footerlink'),
        ('catalog', '0022_remove_product_thumbnail'),
    ]

    operations = [
    ]
