# Generated by Django 4.2.5 on 2024-01-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_merge_20240130_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerlink',
            name='name',
            field=models.CharField(help_text='Footer link name', max_length=50, verbose_name='Footer link'),
        ),
        migrations.AlterField(
            model_name='footerlink',
            name='url',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='footersection',
            name='name',
            field=models.CharField(help_text='Footer section name', max_length=50, verbose_name='Footer Section'),
        ),
    ]
